language : cpp
dist: trusty
sudo: required

os:
  - linux

git:
  depth: false

matrix:
  include:
    - os : linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
          packages:
            - gcc-8
            - g++-8
            - cmake
            - cmake-data
            - libpng-dev
            - libjpeg-turbo8-dev
            - zlib1g-dev
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
        - LINKER_FLAGS=""
install:
  - eval "${MATRIX_EVAL}"

script:
  - cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_EXE_LINKER_FLAGS=${LINKER_FLAGS} .
  - cmake --build . -- VERBOSE=1