language : cpp
dist: trusty
sudo: required
compiler:
  - gcc
os:
  - linux

git:
  depth: false

addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - gcc-7
      - g++-7
      - cmake
      - cmake-data


before_install:
  - sudo apt-get install libpng-dev
  - sudo apt-get install zlib1g-dev
  - cmake --version

install:
  - cmake -G "Unix Makefiles" -DCMAKE_CXX_COMPILER=g++ -DCMAKE_C_COMPILER=gcc -DCMAKE_BUILD_TYPE=Debug .

script:
  - make -j4