language : cpp
sudo: required
compiler:
  - gcc
os:
  - linux

git:
  depth: false

matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-8
            - g++-8

addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake-data
      - cmake

before_install:
  - sudo apt-get install libpng-dev
  - sudo apt-get install zlib1g-dev

install:
  - cmake -G "Unix Makefiles" -DCMAKE_CXX_COMPILER=g++ -DCMAKE_C_COMPILER=gcc -DCMAKE_BUILD_TYPE=Debug .

script:
  - mkdir cmake-build-debug
  - mkdir cmake-build-release
  - cmake --build cmake-build-debug --target all -- -j 4
  - cmake --build cmake-build-release --target all -- -j 4