language : cpp
dist: trusty
sudo: required

os:
  - linux

git:
  depth: false

matrix:
  include:
    - os : linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
          packages:
            - gcc-7
            - g++-7
            - cmake
            - cmake-data
            - libpng-dev
            - zlib1g-dev
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
        - LINKER_FLAGS=""
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-6.0
            - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-6.0 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - clang-6.0
            - libstdc++6
            - libpng-dev
            - zlib1g-dev
      env:
        - MATRIX_EVAL="CC=clang-6.0 && CXX=clang-6.0"
        - LINKER_FLAGS="-stdlib=libc++ -lc++abi"

install:
  - eval "${MATRIX_EVAL}"

script:
  - cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_EXE_LINKER_FLAGS=${LINKER_FLAGS} .
  - cmake --build . -- VERBOSE=1